// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExtractTimestampFromULID(arg1:string):Promise<string>;

export function GenerateULID(arg1:boolean):Promise<string>;

export function GenerateUUID(arg1:boolean):Promise<string>;
