// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateULID(arg1) {
  return window['go']['main']['IDTab']['GenerateULID'](arg1);
}

export function GenerateUUID(arg1) {
  return window['go']['main']['IDTab']['GenerateUUID'](arg1);
}
