// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Beautify(arg1, arg2) {
  return window['go']['main']['JSONTab']['Beautify'](arg1, arg2);
}
