// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Calculate(arg1, arg2) {
  return window['go']['main']['PercentTab']['Calculate'](arg1, arg2);
}
